name: ar_app
description: A Flutter AR Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  arkit_plugin: ^1.0.7
  vector_math: ^2.1.4
  collection: ^1.17.1
  video_player: ^2.7.2
  just_audio: ^0.9.36

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/audio/
    - assets/icon/

flutter_launcher_icons:
  ios: true
  image_path: "assets/icon/icon.png"
